import type { Config } from 'tailwindcss'
import { withAccountKitUi, createColorSet } from '@account-kit/react/tailwind'

// Create a base configuration that includes default utilities
const baseConfig: Config = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-white-0': '#171717',
        'stroke-soft-200': '#464646',
        'text-disabled-300': '#bdbdbd',
        '-Branding-400': '#ff70e5',
        '-Branding-600': '#df1aba',
        'alpha-gray-alpha-10': 'rgba(163, 163, 163, 0.1)',
        'text-soft-400': '#7c7c7c',
        'green-500': '#1fc16b',
        'text-sub-600': '#989898',
        'text-strong-950': '#fff',
        '-Theme-primary-base': '#f7ce02',
        'blue-200': '#c0d5ff',
        'state-success-base': '#1daf61',
        'state-verified-base': '#35ade9',
        'blue-950': '#122368',
        'yellow-200': '#ffecc0',
        'yellow-950': '#624c18',
        'neutral-gray-200': '#dcdcdc',
        'bg-soft-200': '#525252',
        'state-feature-lighter': 'rgba(120, 77, 239, 0.16)',
        'state-feature-dark': '#8c71f6',
        gray: 'rgba(255, 255, 255, 0.12)',
        gold: '#fff142',
        black: '#000',
      },
      spacing: {
        'spacing-spacing-8': '8px',
        'spacing-spacing-16': '16px',
        'spacing-spacing-161': '16px',
        'spacing-spacing-32': '32px',
        'spacing-spacing-4': '4px',
        'spacing-spacing-12': '12px',
        'spacing-spacing-40': '40px',
        'spacing-spacing-14': '14px',
      },
      fontFamily: {
        'Web-title-1-normal': 'Poppins',
        'Web-overline-2X-Small': 'Inter',
      },
      borderRadius: {
        'radius-16': '16px',
        'radius-8': '8px',
        'radius-24': '24px',
        'radius-10': '10px',
        'radius-border-radius-xxs': '4px',
        'radius-28': '28px',
        'radius-full': '999px',
        'radius-4': '4px',
        'radius-6': '6px',
        '3xs': '10px',
        '81xl': '100px',
        '9xl': '28px',
        '980xl': '999px',
        '77xl': '96px',
      },
      padding: {
        '13xl': '32px',
        mini: '15px',
        sm: '14px',
        '3xs': '10px',
        '15xl': '34px',
        '8xl': '27px',
        '3xl': '22px',
        '18xl': '37px',
        '9xl': '28px',
        lgi: '19px',
        '12xs': '1px',
      },
      fontWeight: {
        'font-weight-default-normal': '500',
        'font-weight-default-medium': '600',
      },
      lineHeight: {
        'font-line-height-paragraph': '16px',
        'font-line-height-body-2': '24px',
        'font-line-height-title-2': '24px',
        'font-line-height-body-1': '24px',
      },
      letterSpacing: {
        'font-letter-spacing-none': '0px',
        'font-letter-spacing-xs': '-0.20000000298023224px',
      },
      fontSize: {
        'font-size-paragraph': '12px',
        'font-size-body-2': '14px',
        'font-size-title-1': '18px',
        'font-size-heading-5': '26px',
        'font-size-title-2': '15px',
        'font-size-body-1': '16px',
        lg: '18px',
        '7xl': '26px',
        xs: '12px',
        '2xs': '11px',
        sm: '14px',
        base: '16px',
        mini: '15px',
        inherit: 'inherit',
      },
    },
  },
  // corePlugins: {
  //   preflight: false,
  // },
}

// Apply the Account Kit UI wrapper but ensure it preserves Tailwind defaults
export default withAccountKitUi(
  {
    content: ['./src/**/*.{js,jsx,ts,tsx}'],
    theme: {
      extend: baseConfig.theme?.extend || {},
    },
  },
  {
    // override account kit themes
    colors: {
      'btn-primary': createColorSet('#E82594', '#FF66CC'),
      'fg-accent-brand': createColorSet('#E82594', '#FF66CC'),
    },
    borderRadius: 'md',
  }
) // const config: Config = {//   content: ['./src/**/*.{js,jsx,ts,tsx}'],
//   theme: {
//     extend: {
//       colors: {
//         'bg-white-0': '#171717',
//         'stroke-soft-200': '#464646',
//         'text-disabled-300': '#bdbdbd',
//         '-Branding-400': '#ff70e5',
//         '-Branding-600': '#df1aba',
//         'alpha-gray-alpha-10': 'rgba(163, 163, 163, 0.1)',
//         'text-soft-400': '#7c7c7c',
//         'green-500': '#1fc16b',
//         'text-sub-600': '#989898',
//         'text-strong-950': '#fff',
//         '-Theme-primary-base': '#f7ce02',
//         'blue-200': '#c0d5ff',
//         'state-success-base': '#1daf61',
//         'state-verified-base': '#35ade9',
//         'blue-950': '#122368',
//         'yellow-200': '#ffecc0',
//         'yellow-950': '#624c18',
//         'neutral-gray-200': '#dcdcdc',
//         'bg-soft-200': '#525252',
//         'state-feature-lighter': 'rgba(120, 77, 239, 0.16)',
//         'state-feature-dark': '#8c71f6',
//         gray: 'rgba(255, 255, 255, 0.12)',
//         gold: '#fff142',
//         black: '#000',
//       },
//       spacing: {
//         'spacing-spacing-8': '8px',
//         'spacing-spacing-16': '16px',
//         'spacing-spacing-161': '16px',
//         'spacing-spacing-32': '32px',
//         'spacing-spacing-4': '4px',
//         'spacing-spacing-12': '12px',
//         'spacing-spacing-40': '40px',
//         'spacing-spacing-14': '14px',
//       },
//       fontFamily: {
//         'Web-title-1-normal': 'Poppins',
//         'Web-overline-2X-Small': 'Inter',
//       },
//       borderRadius: {
//         'radius-16': '16px',
//         'radius-8': '8px',
//         'radius-24': '24px',
//         'radius-10': '10px',
//         'radius-border-radius-xxs': '4px',
//         'radius-28': '28px',
//         'radius-full': '999px',
//         'radius-4': '4px',
//         'radius-6': '6px',
//         '3xs': '10px',
//         '81xl': '100px',
//         '9xl': '28px',
//         '980xl': '999px',
//         '77xl': '96px',
//       },
//       padding: {
//         '13xl': '32px',
//         mini: '15px',
//         sm: '14px',
//         '3xs': '10px',
//         '15xl': '34px',
//         '8xl': '27px',
//         '3xl': '22px',
//         '18xl': '37px',
//         '9xl': '28px',
//         lgi: '19px',
//         '12xs': '1px',
//       },
//     },
//     fontWeight: {
//       'font-weight-default-normal': '500',
//       'font-weight-default-medium': '600',
//     },
//     lineHeight: {
//       'font-line-height-paragraph': '16px',
//       'font-line-height-body-2': '24px',
//       'font-line-height-title-2': '24px',
//       'font-line-height-body-1': '24px',
//     },
//     letterSpacing: {
//       'font-letter-spacing-none': '0px',
//       'font-letter-spacing-xs': '-0.20000000298023224px',
//     },
//     fontSize: {
//       'font-size-paragraph': '12px',
//       'font-size-body-2': '14px',
//       'font-size-title-1': '18px',
//       'font-size-heading-5': '26px',
//       'font-size-title-2': '15px',
//       'font-size-body-1': '16px',
//       lg: '18px',
//       '7xl': '26px',
//       xs: '12px',
//       '2xs': '11px',
//       sm: '14px',
//       base: '16px',
//       mini: '15px',
//       inherit: 'inherit',
//     },
//   },
//   plugins: [],
// }

// export default config
